{
 "title": "Cluster Overview",
 "tags": [ "charmed-hpc" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_nodes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(slurm_partition_cpus{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory available",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(slurm_partition_nodes_mem_avail{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total jobs",
   "type": "stat",
   "gridPos": { "h": 14, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_jobs{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total partitions",
   "type": "stat",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_partitions{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total node utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(slurm_nodes_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"} / slurm_nodes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(slurm_partition_nodes_cpus_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}) / sum(slurm_partition_cpus{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(slurm_partition_nodes_mem_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}) / sum(slurm_partition_nodes_mem_avail{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Job statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Running/Pending/Completing jobs",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "slurm_jobs_completing{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Completing jobs"
    },
    {
     "expr": "slurm_jobs_running{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Running jobs"
    },
    {
     "expr": "slurm_jobs_pending{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Pending jobs"
    },
    {
     "expr": "slurm_jobs_completed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Completed jobs"
    },
    {
     "expr": "slurm_jobs{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Total jobs"
    }
   ]
  },
  {
   "title": "Failed/Timed out/Suspended/Cancelled/Preempted jobs",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "slurm_jobs_timeout{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Timed out jobs"
    },
    {
     "expr": "slurm_jobs_failed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Failed jobs"
    },
    {
     "expr": "slurm_jobs_node_failed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Failed jobs (due to Node Failure)"
    },
    {
     "expr": "slurm_jobs_suspended{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Suspended jobs"
    },
    {
     "expr": "slurm_jobs_cancelled{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Cancelled jobs"
    },
    {
     "expr": "slurm_jobs_preempted{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Preempted jobs"
    }
   ]
  },
  {
   "title": "Job state distribution",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_jobs_bootfail{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "BootFail"
    },
    {
     "expr": "slurm_jobs_cancelled{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Cancelled"
    },
    {
     "expr": "slurm_jobs_completed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Completed"
    },
    {
     "expr": "slurm_jobs_completing{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Completing"
    },
    {
     "expr": "slurm_jobs_configuring{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Configuring"
    },
    {
     "expr": "slurm_jobs_deadline{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Deadline"
    },
    {
     "expr": "slurm_jobs_expediting{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Expediting"
    },
    {
     "expr": "slurm_jobs_failed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "slurm_jobs_finished{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Finished"
    },
    {
     "expr": "slurm_jobs_hold{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Hold"
    },
    {
     "expr": "slurm_jobs_node_failed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Node Failed"
    },
    {
     "expr": "slurm_jobs_outofmemory{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Out of Memory"
    },
    {
     "expr": "slurm_jobs_pending{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "slurm_jobs_powerup_node{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "PowerUp Node"
    },
    {
     "expr": "slurm_jobs_preempted{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Preempted"
    },
    {
     "expr": "slurm_jobs_requeued{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Requeued"
    },
    {
     "expr": "slurm_jobs_resizing{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Resizing"
    },
    {
     "expr": "slurm_jobs_running{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "slurm_jobs_signaling{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Signaling"
    },
    {
     "expr": "slurm_jobs_stageout{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "StageOut"
    },
    {
     "expr": "slurm_jobs_suspended{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Suspended"
    },
    {
     "expr": "slurm_jobs_timeout{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Timeout"
    }
   ]
  },
  { "title": "Node statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Allocated/Mixed/Idle nodes",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "slurm_nodes_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Allocated nodes"
    },
    {
     "expr": "slurm_nodes_mixed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Mixed nodes"
    },
    {
     "expr": "slurm_nodes_completing{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Completing nodes"
    },
    {
     "expr": "slurm_nodes_idle{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Idle nodes"
    },
    {
     "expr": "slurm_nodes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Total nodes"
    }
   ]
  },
  {
   "title": "Down/Draining/Error nodes",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "slurm_nodes_down{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Down nodes"
    },
    {
     "expr": "slurm_nodes_draining{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Draining nodes"
    },
    {
     "expr": "slurm_nodes_fail{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Failed nodes"
    },
    {
     "expr": "slurm_nodes_noresp{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Nodes not responding"
    }
   ]
  },
  {
   "title": "Node state distribution",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_nodes_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "slurm_nodes_blocked{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "slurm_nodes_completing{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Completing"
    },
    {
     "expr": "slurm_nodes_down{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Down"
    },
    {
     "expr": "slurm_nodes_drain{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Drain"
    },
    {
     "expr": "slurm_nodes_drained{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Drained"
    },
    {
     "expr": "slurm_nodes_draining{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Draining"
    },
    {
     "expr": "slurm_nodes_fail{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Fail"
    },
    {
     "expr": "slurm_nodes_idle{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "slurm_nodes_maint{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Maintenance"
    },
    {
     "expr": "slurm_nodes_mixed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Mixed"
    },
    {
     "expr": "slurm_nodes_noresp{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "No Response"
    },
    {
     "expr": "slurm_nodes_unknown{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Slurm controller statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job queue size",
     "type": "stat",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "slurm_schedule_queue_len{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scheduler cycles",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 10, "x": 4, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "slurm_schedule_cycle_last{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
       "legendFormat": "Last Cycle Time"
      },
      {
       "expr": "slurm_sched_mean_cycle{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
       "legendFormat": "Mean Cycle Time"
      }
     ]
    },
    {
     "title": "Scheduler depth mean",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 10, "x": 14, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "slurm_sched_mean_depth_cycle{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
       "legendFormat": "Mean of processed jobs during scheduling cycles"
      }
     ]
    },
    {
     "title": "Backfill queue size",
     "type": "stat",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "slurm_bf_queue_len{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backfill scheduler cycles",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 10, "x": 4, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "slurm_bf_cycle_last{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
       "legendFormat": "Backfill Last Cycle"
      },
      {
       "expr": "slurm_bf_mean_cycle{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
       "legendFormat": "Backfill Mean Cycle"
      }
     ]
    },
    {
     "title": "Backfill depth mean",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 10, "x": 14, "y": 65 },
     "targets": [
      {
       "expr": "slurm_bf_depth_mean{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
       "legendFormat": "Mean of processed jobs during backfilling scheduling cycles"
      }
     ]
    },
    {
     "title": "Scheduler threads",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "slurm_server_thread_cnt{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Agents",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "slurm_agent_cnt{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Agent queue size",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "slurm_agent_queue_size{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SlurmDBD queue size",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "slurm_slurmdbd_queue_size{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}