{
 "title": "Node Overview",
 "tags": [ "charmed-hpc" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "title": "Statistics for node $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_node_cpus{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total effective CPUs",
   "type": "stat",
   "description": "The total amount of CPUs that are allocatable to jobs and not reserved for system usage. ",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_node_cpus_effective{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated vs Idle CPUs",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "slurm_node_cpus_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", node=\"$node\"}",
     "legendFormat": "Allocated CPUs"
    },
    {
     "expr": "slurm_node_cpus_idle{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", node=\"$node\"}",
     "legendFormat": "Idle CPUs"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_node_memory_bytes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total effective memory",
   "type": "stat",
   "description": "The total amount of memory this is allocated to jobs and not reserved for system usage.",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_node_memory_effective_bytes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated vs Free memory",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "slurm_node_memory_alloc_bytes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", node=\"$node\"}",
     "legendFormat": "Allocated memory"
    },
    {
     "expr": "slurm_node_memory_free_bytes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", node=\"$node\"}",
     "legendFormat": "Free memory"
    }
   ]
  },
  {
   "title": "Total CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_node_cpus_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", node=\"$node\"} / slurm_node_cpus{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", node=\"$node\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_node_memory_alloc_bytes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", node=\"$node\"} / slurm_node_memory_bytes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", node=\"$node\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}