{
 "title": "Partition Overview",
 "tags": [ "charmed-hpc" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "partition", "label": "Partition", "query": { "query": "label_values(partition)" } }
  ]
 },
 "panels": [
  {
   "title": "Overview of partition $partition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "partition"
  },
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_partition_nodes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_partition_cpus{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory available",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_partition_nodes_mem_avail{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total jobs",
   "type": "stat",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_partition_jobs{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total node utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(slurm_partition_nodes_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"} / slurm_partition_nodes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(slurm_partition_nodes_cpus_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"} / slurm_partition_cpus{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(slurm_partition_nodes_mem_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"} / slurm_partition_nodes_mem_avail{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job statistics for partition $partition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "partition"
  },
  {
   "title": "Running/Pending/Completing jobs",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "slurm_partition_jobs_completing{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Completing jobs"
    },
    {
     "expr": "slurm_partition_jobs_running{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Running jobs"
    },
    {
     "expr": "slurm_partition_jobs_pending{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Pending jobs"
    },
    {
     "expr": "slurm_partition_jobs_completed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Completed jobs"
    },
    {
     "expr": "slurm_partition_jobs{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Total jobs"
    }
   ]
  },
  {
   "title": "Failed/Timed out/Suspended/Cancelled/Preempted jobs",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "slurm_jobs_timeout{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Timed out jobs"
    },
    {
     "expr": "slurm_jobs_failed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Failed jobs"
    },
    {
     "expr": "slurm_jobs_node_failed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Failed jobs (due to Node Failure)"
    },
    {
     "expr": "slurm_jobs_suspended{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Suspended jobs"
    },
    {
     "expr": "slurm_jobs_cancelled{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Cancelled jobs"
    },
    {
     "expr": "slurm_jobs_preempted{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Preempted jobs"
    }
   ]
  },
  {
   "title": "Job state distribution",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_partition_jobs_bootfail{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "BootFail"
    },
    {
     "expr": "slurm_partition_jobs_cancelled{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Cancelled"
    },
    {
     "expr": "slurm_partition_jobs_completed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Completed"
    },
    {
     "expr": "slurm_partition_jobs_completing{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Completing"
    },
    {
     "expr": "slurm_partition_jobs_configuring{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Configuring"
    },
    {
     "expr": "slurm_partition_jobs_deadline{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Deadline"
    },
    {
     "expr": "slurm_partition_jobs_expediting{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Expediting"
    },
    {
     "expr": "slurm_partition_jobs_failed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "slurm_partition_jobs_finished{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Finished"
    },
    {
     "expr": "slurm_partition_jobs_hold{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Hold"
    },
    {
     "expr": "slurm_partition_jobs_node_failed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Node Failed"
    },
    {
     "expr": "slurm_partition_jobs_outofmemory{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Out of Memory"
    },
    {
     "expr": "slurm_partition_jobs_pending{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "slurm_partition_jobs_powerup_node{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "PowerUp Node"
    },
    {
     "expr": "slurm_partition_jobs_preempted{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Preempted"
    },
    {
     "expr": "slurm_partition_jobs_requeued{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Requeued"
    },
    {
     "expr": "slurm_partition_jobs_resizing{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Resizing"
    },
    {
     "expr": "slurm_partition_jobs_running{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "slurm_partition_jobs_signaling{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Signaling"
    },
    {
     "expr": "slurm_partition_jobs_stageout{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "StageOut"
    },
    {
     "expr": "slurm_partition_jobs_suspended{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Suspended"
    },
    {
     "expr": "slurm_partition_jobs_timeout{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Node statistics for partition $partition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "partition"
  },
  {
   "title": "Allocated/Mixed/Idle nodes",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "slurm_nodes_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Allocated nodes"
    },
    {
     "expr": "slurm_partition_nodes_mixed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Mixed nodes"
    },
    {
     "expr": "slurm_nodes_completing{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Completing nodes"
    },
    {
     "expr": "slurm_nodes_idle{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Idle nodes"
    },
    {
     "expr": "slurm_nodes{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Total nodes"
    }
   ]
  },
  {
   "title": "Down/Draining/Error nodes",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "slurm_nodes_down{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Down nodes"
    },
    {
     "expr": "slurm_nodes_draining{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Draining nodes"
    },
    {
     "expr": "slurm_nodes_fail{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Failed nodes"
    },
    {
     "expr": "slurm_nodes_noresp{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Nodes not responding"
    }
   ]
  },
  {
   "title": "Node state distribution",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_partition_nodes_alloc{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "slurm_partition_nodes_blocked{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "slurm_partition_nodes_cg{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Completing"
    },
    {
     "expr": "slurm_partition_nodes_down{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Down"
    },
    {
     "expr": "slurm_partition_nodes_drain{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Drain"
    },
    {
     "expr": "slurm_partition_nodes_drained{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Drained"
    },
    {
     "expr": "slurm_partition_nodes_draining{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Draining"
    },
    {
     "expr": "slurm_partition_nodes_fail{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Fail"
    },
    {
     "expr": "slurm_partition_nodes_idle{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "slurm_partition_nodes_maint{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Maintenance"
    },
    {
     "expr": "slurm_partition_nodes_mixed{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Mixed"
    },
    {
     "expr": "slurm_partition_nodes_no_resp{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "No Response"
    },
    {
     "expr": "slurm_partition_nodes_unknown{juju_model_uuid=~\"$juju_model_uuid\", juju_model=~\"$juju_model\",juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\", partition=\"$partition\"}",
     "legendFormat": "Unknown"
    }
   ]
  }
 ]
}