[project]
name = "slurmctld"
version = "0.0"
requires-python = "==3.12.*"
dependencies = [
    "ops",
    "slurmutils",
    "influxdb",
    "netifaces-plus",
    "hpc-libs",
    "cosl",
    "slurm-ops",
]

[tool.repository]
libraries = ["grafana-agent.cos_agent", "filesystem-client.mount_info"]
